name: stylish
description: A set of UI elements and patterns with rules and guidelines.
version: 0.1.0

homepage: https://G1Joshi.dev/docs/stylish/about/
repository: https://github.com/G1J0SHI/stylish

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  analysis_options: ^2.0.1

flutter:
